server:
  port: 8765

spring:
  application:
    name: service-feign

eureka:
  client:
    service-url:
      defauleZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    instance-id: service-feign

# Feign是自带断路器的，在D版本的Spring Cloud之后，它没有默认打开
feign:
  hystrix:
    enabled: true