server:
  port: 8763

spring:
  application:
    name: service-hi
  zipkin:
    base-url:
      http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone:  http://eureka8761.com:8761/eureka/, http://eureka8769.com:8769/eureka/
info:
  app.name: service-hi
